- hosts: network
  become: yes
  tasks:
    - name: Install zsh
      apt:
        name: zsh
        state: present

    - name: Install git
      apt:
        name: git
        state: present

    - name: Install oh-my-zsh for the current user
      shell: sh -c "$(wget https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh -O -)"
      args:
        creates: ~/.oh-my-zsh
        executable: /bin/bash

    - name: Set zsh as the default shell for the current user
      user:
        name: "{{ ansible_user_id }}"
        shell: /bin/zsh

    - name: Set theme to bira in .zshrc
      lineinfile:
        path: ~/.zshrc
        regexp: '^ZSH_THEME=".*"'
        line: 'ZSH_THEME="bira"'
