
Vagrant.configure("2") do |config|

  config.vm.box = "generic/ubuntu2204"
  config.vm.network "private_network", ip: "10.11.12.13", netmask: "255.255.255.0"
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
  end

end
